MRCA_priors <- list(
  ArabanaWangkangurru.prior = c("Arabana", "Wangkangurru"),
  Arandic.prior = c("Alyawarr", "Antekerrepenhe", "CentralAnmatyerr", "Kaytetye", 
                    "WesternArrarnta"),
  Bandjalangic.prior = c("Bandjalang", "Githabul", "Minjungbal", "NerangCreek",
                         "NggoiMwoi", "TweedRiverandPointDangar", "Yugambeh"),
  Bigambalic.prior = c("Bigambal", "GlenInnes", "Tenterfield"),
  Central_NSW.prior = c("Gamilaraay", "Kamilaroi", "Muruwari", "Ngiyambaa", 
                        "Wailwan", "Wiradjuri", "Yuwaalaraay"),
  Durubulic.prior= c("Coobenpil", "Durubul", "Guwar", "Janday", "Yagara", "Yugarabul"),
  EastKarnic.prior = c("Garlali", "Kungadutyi", "Kungkari", "Pirriya", "Punthamara",
                       "Wangkumara", "WangkumaraMcDWur"),
  Gumbaynggiric.prior = c("Gumbaynggir", "Yaygirr"),
  Kalkatungic.prior = c("Kalkatungu", "Yalarnnga"),
  Kanyara_Mantharta.prior = c("Jiwarli", "Payungu", "Purduna", "Thalanyji", 
                              "Tharrgari", "Warriyangga", "Yingkarta"),
  Karnic.prior = c("Yanda", "Badjiri", "Guwa", "CoopersCreek", "Diyari", "Karuwali",
                   "Mithaka", "MountFreelingDiyari", "Ngamini", "Nhirrpi", "Yandruwandha",
                   "Yarluyandi", "Yawarrawarrka"),
  Kartu.prior = c("Badimaya", "ChampionBay", "IrwinMurchison", "Kalaamaya", "Malgana", 
                  "MuliarraTribe", "Nhanta", "Wajarri"),
  Kulin.prior = c("Bindjali", "Bunganditj", "Colac", "Gunditjmara", "HOPKINSRIVER", 
                  "Keerraywoorroong", "LakeHindmarsh", "MathiMathi", "Piangil", 
                  "THETATIARRACOUNTRY", "Tjapwurrung", "Warrnambool", "Wathawurrung", 
                  "Wathiwathi", "WembaWemba", "Woiwurrung"),
  Lower_Murray.prior = c("Balkurra", "Keramin", "NedsCornerStation", "Ngaiawang", 
                         "Ngarrindjeri", "PytuReach", "Wellington", "YithaYitha"),
  Marrngu.prior = c("Karajarri", "KarajarriNW", "MangalaMcK", "MangalaNW", 
                    "NorthernMangarla", "NorthernNyangumarta", "Nyangumarta"),
  Mayi.prior = c("MayiKulan", "MayiKutuna", "MayiThakurti", "MayiYapi", "Ngawun", 
                 "Wanamara"),
  Ngayarta.prior = c("Kariyarra", "Kurrama", "Martuthunira", "Ngarla", "Ngarluma", 
                     "Nyamal", "Panyjima", "Yindjibarndi", "Yinhawangka"),
  Ngumpin_Yapa.prior = c("Bilinarra", "Gurindji", "Jaru", "JaruMcC", "Jiwarliny", 
                         "Malngin", "Mudburra", "MudburraMcC", "Ngardily", "Ngarinyman", 
                         "SouthernWalmajarri", "WalmajarriBilliluna", "WalmajarriHR", 
                         "WalmajarriNW", "Warlmanpa", "Warlpiri", "Warumungu"),
  ParaMaric.prior = c("AghuTharrnggala", "Alngith", "Aminungo", "Ayapathu", "Barna", 
                      "BarrowPoint", "Belyando", "BidyaraGungabula", "Bindal", "Biri", 
                      "Coonambella", "Dharawala", "Dharumbal", "Djabugay", "Dyirbal", 
                      "FlindersIsland", "Gangulu", "GraniteRange", "Gudang", "Gudjal", 
                      "GuguBadhun", "Gugumini", "Gunggari", "Gunya", "GuuguYimidhirr", 
                      "Guwamu", "Ikarranggal", "Injinoo", "KKY", "KLY", "Kaanju", 
                      "KokNar", "KokoBera", "KuguNganhcara", "Kukatj", "KukuWura", 
                      "KukuYalanji", "Kunjen", "Kurtjar", "KuukThaayorre", "KuukuYau", 
                      "Linngithigh", "LowerBurdekin", "Mabuiag", "Margany", "Mbabaram", 
                      "Mbakwithi", "Mbiywom", "Mpalityan", "NatalDowns", "Nggoth", 
                      "Ntrangith", "Nyawaygi", "Olkola", "Pakanh", "Tagalag", "Tambo", 
                      "Thaynakwith", "Umpila", "Umpithamu", "UpperParoo", "Uradhi", 
                      "UwOykangand", "Wadjabangayi", "Walangama", "Wargamay", "Warungu", 
                      "WikMuminh", "WikMungkan", "WikNgatharr", "Wulguru", "Yadhaykenu", 
                      "Yambina", "Yidiny", "Yiningay", "Yinwum", "YirYoront", "Yirandali"),
  PittaPittic.prior = c("KingsCreekandtheGeorginaRiver", "PittaPitta", 
                        "RoxburghDowns-LowerGeorgina", "Wangkayutyuru"),
  Tangkic.prior = c("Ganggalida", "Kayardild", "Lardil", "Minkin", "Nguburindi", 
                    "Yangarella", "Yangkaal"),
  Thura_Yura.prior = c("Adnyamathanha", "Guyani", "Kaurna", "Narrungga", "Ngadjuri", 
                       "Nukunu", "Parnkala", "Wirangu"),
  Waba_Kabi.prior = c("Batyala", "Bayali", "Dalla", "DawsonRiver", "Duungidjawu", 
                      "GoorengGooreng", "MaryRiverandBunyaBunyaCountry", "UpperBrisbaneRiver", 
                      "WakaWaka"),
  Warluwaric.prior = c("Bularnu", "Wakaya", "Warluwarra", "Yanyuwa", "Yindjilandji"),
  WatiOriginate.prior = c("Kartujarra", "Kukatja", "Manjiljarra", "MartuWangka", 
                          "Ngaanyatjarra", "PintupiLuritja", "Pitjantjatjara", 
                          "Wangkajunga", "Wangkatja", "Warnman", "Yulparija"),
  Yardli.prior = c("Malyangapa", "Wadikali", "Yardliyawarra"),
  Yolngu.prior = c("Dhangu", "Dhayyi", "Dhuwal", "Dhuwala", "Djambarrpuyngu", "Djapu", 
                   "Djinang", "Golpa", "Gumatj", "Gupapuyngu", "Rirratjingu", "Ritharrngu", 
                   "Yannhangu", "Zorc"),
  Yotayotic.prior = c("Dhudhuroa", "Pallanganmiddang", "YabulaYabula", "YortaYorta"),
  Yuin_Kuri.prior = c("Awabakal", "Birrpayi", "Darkinyung", "Dharawal", "Dharuk", 
                      "Dhurga", "Gundungurra", "Hawkesbury", "Iyora", "Jaitmatang", 
                      "Karree", "Katthang", "Moneroo", "Ngarigu", "Ngunawal", 
                      "PortMacQuarie", "SteeleGDG", "Thanggatti", "Thurrawal"),
  PaakantyiRegion.prior = c("Kurnu", "Paakantyi"),
  SouthWest.prior = c("Bibbulman", "Eucla", "Kaniyang", "Mirniny", "NewNorciaandLeschenaultBay", 
                      "Ngadjumaya", "Nyungar", "Pinjarra", "Wardandi", "Watjuk"),
  stringsAsFactors = FALSE
)